version: "3.7"

services:
  traefik:
    image: "traefik:v2.1"
    command:
      - "--providers.docker=true"
    container_name: "traefik"
    hostname: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
    restart: always
  whoami:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.service=route-to-authorize-api"
      - "traefik.http.routers.whoami.entrypoints=web"
networks:
  default:
    external:
      name: $DEFAULT_NETWORK