## STATIC CONFIGURATION
log:
  level: INFO

api:
  insecure: true
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "traefik.yml"

## DYNAMIC CONFIGURATION
http:
  routers:
    route-to-server:
      rule: "PathPrefix(`/api/`)"
      service: route-to-api-service
      middlewares:
        - "auth"
        - "replacepath-regex"
      priority: 1000
      entryPoints:
        - web
    route-to-auth:
      rule: "Path(`/login`)"
      service: "route-to-authorize-api"
      middlewares:
        - "replacepath-authorize"
      priority: 0
      entryPoints:
        - web
  middlewares:
    auth:
      forwardAuth:
        address: "http://sso_service:4445/internal_api/validate"
        trustForwardHeader: true
    replacepath-authorize:
      replacePath:
        path: "/internal_api/authorize"
     # this demo replace path by regex
    replacepath-regex:
      replacePathRegex:
        regex: "^/api/(.*)"
        replacement: "/internal_api/$1"
  services:
    route-to-authorize-api:
      networks:
        - backend
      loadBalancer:
        servers:
          - url: "http://sso_service:4445"
    route-to-api-service:
      networks:
        - backend
      loadBalancer:
        servers:
#          - url: "http://host.docker.internal:4445/health"
          - url: "http://sso_service:4445"